### ISSUE TITLE
Add flag to pass in filenames to leave unmodified

### ISSUE THREAD

**Issue by ktiedt** [PolymerLabs/polyup#11]
I ran polyup against this project https://github.com/christopheclc/polymer-date-picker/ as a test, and it behaves a tad oddly.
```
polyup polymer-date-picker.html
```

1) if no --overwrite is given it inlines moment.min.js as well...
2) if --overwrite is given it aborts because of moment.min.js being outside CWD (understandable precaution but, really it should ignore it right?

**Comment by rictic** [comment]
How about a flag of files not to upgrade. I'd rather that than quietly ignoring the script include.

It's intended to work fine without the `--overwrite` flag. Without that flag, polyup writes the filename it will write, followed by the contents it will write.

**Comment by ktiedt** [comment]
I would be fine with that distinction, my comment with --overwrite vs w/o was simply that one aborted and the other did not (which was slightly inconsistent behavior)
