### ISSUE TITLE
0.5 attribute?="" bindings get transformed into invalid computed property names

### ISSUE THREAD

**Issue by ebidel** [PolymerLabs/polyup#19]
Running the online tool (http://polymerlabs.github.io/polyup/), 

0.5 code:

    <div hidden?="{{!fetchError}}">

polyup 1.0 transformed code:

    <div hidden$="{{computeHidden?(fetchError)}}">

The `computeHidden?()` that gets created on the prototype is an invalid JS method name, and it throws.

**Comment by rictic** [comment]
Thanks for the bug report!
