### ISSUE TITLE
Default host attributes that are listeners get transformed incorrectly

### ISSUE THREAD

**Issue by ebidel** [PolymerLabs/polyup#20]
0.5 code:

    <polymer-element name="chromedash-featurelist" on-scroll="{{onScrollList}}" on-keyup="{{onKeyUp}}">

gets transformed into:

    hostAttributes: {
        on-scroll: '{{onScrollList}}',
        on-keyup: '{{onKeyUp}}',
      },

This should instead be under `listeners` and from `{{}}`.

**Comment by rictic** [comment]
Thanks for the bug report! 

Makes sense. Can we assume that any host attribute that begins with `on-` is a listener?

**Comment by ebidel** [comment]
Think so. That's a polymer specific feature.
