### ISSUE TITLE
Upgrade expressions that use tokenList

### ISSUE THREAD

**Issue by rictic** [PolymerLabs/polyup#27]

**Comment by bdittes** [comment]
Could we generalize this to 'support filter expressions'?
i.e. turn {{a+b | myFilter(2) | tokenList}} into tokenList(myFilter(a+b, 2)) ?

**Comment by rictic** [comment]
Yep, that's #28. 

I made tokenList a separate bug because we may have to inject a tokenList function into the element prototype if we notice that the element uses it.
