### ISSUE TITLE
Minimize upgrade diff by adding option to just reformat code first

### ISSUE THREAD

**Issue by davidmaxwaterman** [PolymerLabs/polyup#52]
I am attempting to update this app :

<https://github.com/01org/nlpljs/tree/master/example-app>

it has 32 polymer elements :

<https://github.com/01org/nlpljs/tree/master/example-app/app/content_push>

So, the upgrade effort is significant. Polyup has helped, but it makes a lot of unnecessary diffs that obfuscate the real changes.

It occurred to me that it might be a worthwhile step to preprocess the code into the 'expected' coding style before running polyup, so that the real changes can be seen more clearly.

Does polyup presume certain coding style? Would it help to convert the code into that style prior to using polyup, and is there a tool to do this?

**Comment by rictic** [comment]
For the most part polyup doesn't assume a coding style, most non-functionality changes that you're seeing are just due to the limitations of the parsers that we use. They throw away some information, e.g. attribute quoting style in HTML, whitespace style in javascript, so when it's time for polyup to write your modified code back out to disk it's got to make some guesses as to how to format.

I can see what you're saying about the diffs being a mixture of stylistic chages and upgrading to 1.0 semantics. What if we offered a command line flag `--just_reformat` that would pass your code through these parsers but without applying any of polyup's modifications, so that you could first see that diff and make a commit. Then you could run polyup for real and the diff would consist purely of the 0.5 -> 1.0 changes.

**Comment by davidmaxwaterman** [comment]
Hrm, yes, that'd do it, I think. If you *can* choose a format, I'd prefer you do so and it be the Google one, of course :)

I had been contemplating using this, both before, and after :

<http://jscs.info/overview.html>

We had been trying to stick to Google's style guide, but haven't been entirely successful.

**Comment by rictic** [comment]
For javascript there's also [clang-format](http://clang.llvm.org/docs/ClangFormat.html), which is super fast and supports google-style for javascript.

**Comment by davidmaxwaterman** [comment]
`Vim Integration` - now you're talking :)

**Comment by davidmaxwaterman** [comment]
I was wondering if it was viable for us to minimize the diff using this option, and then only apply the minimized diff to the original code...I might give that a try, but I wondered what you thought.

**Comment by rictic** [comment]
Hm, you could do a workflow like:

```
git checkout -b temp-work-branch
polyup my-component.html --overwrite --just_reformat
git commit -a -m 'Boring reformat'
polyup my-component.html --overwrite
git commit -a -m 'Run polyup for real.'
git checkout master
git cherry-pick temp-work-branch
```

YMMV but odds are decent that the cherry-pick would have a bunch of conflicts, which may not make it worth it.

**Comment by davidmaxwaterman** [comment]
(should have been `--only_reformat` in the example above - perhaps you could edit it, in case someone else tries it? thanks)

When I try this on [this](https://github.com/01org/nlpljs/blob/master/example-app/app/content_push/cp-document.html) file, I get a crash :

```
$ polyup app/content_push/cp-document.html --overwrite --only_reformat
Error attempting to upgrade app/content_push/cp-document.html


/home/davidmaxwaterman/.nvm/versions/node/v0.12.3/lib/node_modules/polyup/dist/node_main.js:111
  throw e;
        ^
Error: Line 326: Unexpected token -
    at throwError (/home/davidmaxwaterman/.nvm/versions/node/v0.12.3/lib/node_modules/polyup/node_modules/espree/espree.js:2070:17)
    at throwUnexpected (/home/davidmaxwaterman/.nvm/versions/node/v0.12.3/lib/node_modules/polyup/node_modules/espree/espree.js:2133:5)
    at parseObjectProperty (/home/davidmaxwaterman/.nvm/versions/node/v0.12.3/lib/node_modules/polyup/node_modules/espree/espree.js:2600:13)
    at parseObjectInitialiser (/home/davidmaxwaterman/.nvm/versions/node/v0.12.3/lib/node_modules/polyup/node_modules/espree/espree.js:2705:20)
    at parsePrimaryExpression (/home/davidmaxwaterman/.nvm/versions/node/v0.12.3/lib/node_modules/polyup/node_modules/espree/espree.js:2838:16)
    at parseLeftHandSideExpressionAllowCall (/home/davidmaxwaterman/.nvm/versions/node/v0.12.3/lib/node_modules/polyup/node_modules/espree/espree.js:2995:57)
    at parsePostfixExpression (/home/davidmaxwaterman/.nvm/versions/node/v0.12.3/lib/node_modules/polyup/node_modules/espree/espree.js:3044:12)
    at parseUnaryExpression (/home/davidmaxwaterman/.nvm/versions/node/v0.12.3/lib/node_modules/polyup/node_modules/espree/espree.js:3104:16)
    at parseBinaryExpression (/home/davidmaxwaterman/.nvm/versions/node/v0.12.3/lib/node_modules/polyup/node_modules/espree/espree.js:3196:12)
    at parseConditionalExpression (/home/davidmaxwaterman/.nvm/versions/node/v0.12.3/lib/node_modules/polyup/node_modules/espree/espree.js:3257:12)
[example-app]$ 
```

Any thoughts?

**Comment by rictic** [comment]
That's weird, what version of polyup are you using? I'm unable to reproduce that error locally or with the online version at http://polymerlabs.github.io/polyup/

I've been fixing bugs at a pretty steady rate the past few weeks so it's possible you're hitting a bug in an old version.

**Comment by davidmaxwaterman** [comment]
possibly...I am wondering if I actually made an error, so I'll try again. I suspect I actually ran it on a file that had already had been processed by polyup...but not 100%...need to confirm again.

**Comment by davidmaxwaterman** [comment]
I don't think I'm going to get a chance to look into it again, and I am pretty sure you're right about using an old version. I'll try to make sure I test with the latest next time - sorry for the noise.

**Comment by davidmaxwaterman** [comment]
OK, I've had the chance to try it again, on [this](https://github.com/01org/nlpljs/blob/mw-polymer-1.0-upgrade/example-app/app/content_push/cp-display.html) file...and, indeed, my mileage *did* vary :

```
$ git cherry-pick temp-work-branch
error: could not apply 220d1dc... Run polyup for real.
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
```

However, when I examine the conflicts, it does look quite a lot cleaner than I've been used to.

Having said that, there is one part of the diff that I find a bit concerning - this :

```
      <div id="slider_wrapper" vertical justified layout
           class="{{ {'hide': !sliderVisible}|tokenList }}"
           on-mouseover="onSliderMouseOver"
           on-mouseout="onSliderMouseOut">
```

comes out as :

```
      <div id="slider_wrapper" vertical="" justified="" layout=""
        on-mouseover="onSliderMouseOver"
        on-mouseout="{{computeClass2(sliderVisible, tokenList)}}"
        class$="{{computeClass(sliderVisible, tokenList)}}">
```

and that looks quite wrong to me - the `on-mouseout` binding. I am wondering if that isn't to do with polyup directly, but actually merging issue...not sure. Another possibility is that it is due to the re-ordering of attributes, and that is causing a merge problem.

One possible improvement is clear - it would be much better if attributes that were not assigned any value, would remain that way in polyup's output. IE, in the above, `vertical`, `justified`, and `layout`, but my code has such things 'all over it' and the appended `=""` results in quite unnecessary noise in the output, and quite probably causes some problems. There also seems to be blank lines removed - not sure why this technique doesn't 'avoid' that.

Any thoughts on this? I think it is actually quite a bit better than the previous attempt (I'm not sure why this file escaped conversion - I guess there was some complication with the js files <script>'d in?).

Overall...a much better 'diff' than before, I think.

**Comment by rictic** [comment]
The on-mouseout error is https://github.com/PolymerLabs/polyup/issues/81 -- I'm working on it.

The `vertical=""` mess is https://github.com/PolymerLabs/polyup/issues/56 -- I'll take a stab at this as well. It's tricky because that's how the HTML parser we're using treats empty string attributes.
