### ISSUE TITLE
PolyUp should recognize core-drawer-toggle and convert to paper-drawer-toggle

### ISSUE THREAD

**Issue by barakhub** [PolymerLabs/polyup#70]
The core-drawer-toggle is handy in a core-drawer-panel, and should be converted accordingly to paper-drawer-toggle in Polymer 1.0.

**Comment by rictic** [comment]
Thanks for the bug report! I'll look into it.

**Comment by rictic** [comment]
Hm, I'm unable to reproduce this. The core layout elements seem to upgrade just fine as far as I can tell. For example, polyup transforms [this file](https://github.com/PolymerLabs/polyup/blob/052fa5ee3f7690db161436b9c6993730dc38b91c/test/fixtures/scaffold_elements.html) into [this](https://github.com/PolymerLabs/polyup/blob/052fa5ee3f7690db161436b9c6993730dc38b91c/test/fixtures/scaffold_elements.html.out).

Is it possible that you're using an older version? If there's something about the element in particular that wasn't upgraded that you expected it to, let me know.

**Comment by barakhub** [comment]
Apparently, I wasn't clear in my bug report.
What's missing in the PolyUp conversion is not covered by the example you provided. Assume the following in your example:
`<paper-icon-button id="navicon" icon="menu" core-drawer-toggle></paper-icon-button>`
(I only added the core-drawer-toggle attribute)

This should be converted to:
`<paper-icon-button id="navicon" icon="menu" paper-drawer-toggle></paper-icon-button>`

If that's the case, the addEventListener code is not needed, as the drawer panel handles that automatically. This is what's missing from PolyUp.
