### ISSUE TITLE
allow polyup to be re-run on already polup'd files?

### ISSUE THREAD

**Issue by davidmaxwaterman** [PolymerLabs/polyup#83]
I started my upgrade process quite some time ago, and you keep fixing bugs... ;)

Since I am working through all the files, trying to fix the bugs manually, as well as the more cosmetic aspects that change, it isn't too desirable to start again from scratch; but I'd equally like to be able to use the newer fixed versions of polyup.

It does sound very difficult, but I wonder if there might be a way to allow polyup to take an already polyup'd file as input and only change the bits that haven't been done.

Yeah, I thought not, but, if you don't ask...

Perhaps there is some way to actually validate a polymer element? Linting (inlinelint) helps, but it doesn't catch things that interface between html and javascript - there are lots of javascript function and property names that are put as attribute values in html. It'd be great to be able to have a polylint utility...different to polyup, for sure, but somehow seems quite similar too.

**Comment by rictic** [comment]
Finally catching up on the backlog after the summit! 

For catching these issues I'd recommend checking out polylint (as you heard at the summit :): https://github.com/PolymerLabs/polylint

As far as being able to rerun polyup on a file that's partially 1.0 and partially 0.5 and have it do some of the new transforms added in recent versions, that's super tricky. I don't think I'll be able to support that.
