### ISSUE TITLE
In AfterUserGuide.md and README.md, web-components-ready should be WebComponentsReady

### ISSUE THREAD

**Issue by brian-cruickshank** [PolymerLabs/polyup#91]
AfterUserGuide.md  Line 85:
`window.addEventListener('web-components-ready', function() { ... });`
should be
`window.addEventListener('WebComponentsReady', function() { ... });`

README.md Line 148:
`Replace addEventListener('polymer-ready', ...) with addEventListener('web-components-ready', ...)`
should be
`Replace addEventListener('polymer-ready', ...) with addEventListener('WebComponentsReady', ...)`

see https://www.polymer-project.org/1.0/docs/migration.html#polymer-ready

When I tried it with Polymer 1.1.2, the WebComponentsReady event fired, but web-components-ready did not fire.

**Comment by rictic** [comment]
Good catch!
