### ISSUE TITLE
element-mapping.js: Replace paper-dropdown with paper-menu-button

### ISSUE THREAD

**Issue by brian-cruickshank** [PolymerLabs/polyup#92]
Currently, paper-dropdown is replaced with iron-dropdown, which needs non trivial manual changes to get to work properly.

A better approach would be to replace paper-dropdown with paper-menu-button 
https://elements.polymer-project.org/elements/paper-menu-button?view=demo:demo/index.html

**Comment by rictic** [comment]
Looking at the [source](https://github.com/Polymer/paper-dropdown/blob/master/demo.html) code of the 0.5 paper-dropdown [demo](https://www.polymer-project.org/0.5/components/paper-dropdown/demo.html) I'm not sure that I agree.

`paper-dropdown` is [documented as](https://github.com/Polymer/paper-dropdown/blob/master/paper-dropdown.html#L13) a building block for making a dropdown-based UI component like `paper-dropdown-menu` or `paper-menu-button`, and the closest analog to that in the 1.0 world is iron-dropdown (plus a paper-material for the shadow effect).
